import type { ProviderComplianceRecord } from "./contracts.js";

export const providerComplianceRegistry: readonly ProviderComplianceRecord[] = [
  {
    provider: "rdap",
    termsUrl: "https://www.iana.org/assignments/rdap-dns",
    commercialStatus: "ALLOWED",
    authentication: "None; registry-specific policies apply",
    cost: "R$ 0",
    quota: "Registry-specific; respect 429 and Retry-After",
    dataSent: "Domain name to authoritative registry",
    retention: "Normalized registration metadata only, ephemeral in MVP",
    caching: "24h bootstrap; domain TTL 24h when allowed",
    redistribution: "No registrant contact republishing",
    attribution: "Registry source URL retained",
    lastReviewed: "2026-08-30",
    enabled: true,
    killSwitch: "PROVIDER_RDAP_ENABLED",
  },
  {
    provider: "dns-direct",
    termsUrl: "https://nodejs.org/api/dns.html",
    commercialStatus: "ALLOWED",
    authentication: "None",
    cost: "R$ 0",
    quota: "Local resolver operational limits",
    dataSent: "Domain to configured DNS resolver",
    retention: "Ephemeral result; TTL-aware future cache",
    caching: "No persistent cache in MVP",
    redistribution: "Normalized public records only",
    attribution: "Direct DNS observation",
    lastReviewed: "2026-08-30",
    enabled: true,
    killSwitch: "PROVIDER_DNS_ENABLED",
  },
  {
    provider: "tls-direct",
    termsUrl: "https://nodejs.org/api/tls.html",
    commercialStatus: "ALLOWED",
    authentication: "None",
    cost: "R$ 0",
    quota: "Application concurrency limits",
    dataSent: "TLS handshake with target",
    retention: "Certificate metadata only",
    caching: "No persistent cache in MVP",
    redistribution: "Observed metadata only",
    attribution: "Direct TLS observation",
    lastReviewed: "2026-08-30",
    enabled: true,
    killSwitch: "PROVIDER_TLS_ENABLED",
  },
  {
    provider: "transparency-passive",
    termsUrl: "docs/PROVIDERS.md",
    commercialStatus: "CONDITIONAL",
    authentication: "None",
    cost: "R$ 0",
    quota: "One homepage plus at most 10 relevant same-origin pages; depth 1, concurrency 2, 2 MiB aggregate budget",
    dataSent: "Normal HTTP request to submitted origin",
    retention: "Signals only; raw HTML discarded",
    caching: "No persistent cache in MVP",
    redistribution: "No raw page redistribution",
    attribution: "Submitted origin",
    lastReviewed: "2026-08-30",
    enabled: true,
    killSwitch: "PROVIDER_TRANSPARENCY_ENABLED",
  },
  {
    provider: "google-web-risk",
    termsUrl: "https://cloud.google.com/web-risk/docs",
    commercialStatus: "ALLOWED",
    authentication: "Google Cloud credentials and billing",
    cost: "Free allowance may exist; billing account required",
    quota: "Provider/project quota",
    dataSent: "Submitted URL in Lookup mode",
    retention: "Provider policy",
    caching: "Provider policy",
    redistribution: "Provider policy",
    attribution: "Per provider terms",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_WEB_RISK_ENABLED",
    disabledReason: "DISABLED_NO_CREDENTIALS",
  },
  {
    provider: "virus-total-public",
    termsUrl: "https://docs.virustotal.com/reference/public-vs-premium-api",
    commercialStatus: "PROHIBITED",
    authentication: "Backend x-apikey; personal credential allowed only in explicit LOCAL_NONCOMMERCIAL loopback runtime",
    cost: "Public API is free only for eligible non-commercial/academic use; commercial use requires a paid agreement",
    quota: "Public API: 4 requests/minute and 500/day; no SLA",
    dataSent: "Nothing while disabled; personal local mode sends only registrable domain and normalized origin root",
    retention: "No raw response persistence; standard submissions are explicitly prohibited by the adapter",
    caching: "Bounded in-memory HMAC-keyed cache only in an eligible personal local runtime",
    redistribution: "Raw response redistribution is not authorized",
    attribution: "VirusTotal source and official domain report URL when a permitted runtime exists",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_VT_ENABLED",
    disabledReason: "DISABLED_BY_POLICY",
  },
  {
    provider: "urlhaus-community",
    termsUrl: "https://urlhaus.abuse.ch/api/",
    commercialStatus: "CONDITIONAL",
    authentication: "Free abuse.ch Auth-Key required",
    cost: "Community API is free under fair use; commercial or for-profit use may require a paid enhanced API",
    quota: "Fair-use limits; bulk feeds must not be fetched more often than documented",
    dataSent: "No URL is sent while disabled",
    retention: "Not applicable while disabled",
    caching: "Not applicable while disabled",
    redistribution: "Subject to abuse.ch fair-use terms",
    attribution: "URLhaus / abuse.ch",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_URLHAUS_ENABLED",
    disabledReason: "DISABLED_BY_POLICY",
  },
  {
    provider: "phishtank",
    termsUrl: "https://phishtank.org/api_info.php",
    commercialStatus: "ALLOWED",
    authentication: "Free application key recommended for a practical rate limit; descriptive User-Agent required",
    cost: "Free for commercial and non-commercial API use according to the official FAQ",
    quota: "Dynamic rate limits; HTTP 509 when exceeded",
    dataSent: "No URL is sent while disabled",
    retention: "Not applicable while disabled",
    caching: "Periodic local database is recommended for sustained usage",
    redistribution: "Community data; attribution and current Cisco terms remain applicable",
    attribution: "PhishTank / Cisco Talos",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_PHISHTANK_ENABLED",
    disabledReason: "DISABLED_NOT_PROVISIONED",
  },
  {
    provider: "consumer-gov-open-data",
    termsUrl: "https://www.consumidor.gov.br/pages/dadosabertos/externo/",
    commercialStatus: "ALLOWED",
    authentication: "Nenhuma para os arquivos mensais de dados abertos",
    cost: "R$ 0; ingestão local do snapshot não provisionada no MVP",
    quota: "Publicação mensal em lote; não é consulta operacional por URL",
    dataSent: "Nenhum dado enviado no MVP",
    retention: "Nenhum dado coletado no MVP",
    caching: "Não aplicável",
    redistribution: "Não aplicável",
    attribution: "Consumidor.gov.br / Senacon — dados abertos",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_CONSUMER_GOV_OPEN_DATA_ENABLED",
    disabledReason: "DISABLED_NOT_PROVISIONED",
  },
  {
    provider: "reclame-aqui-manual",
    termsUrl: "https://www.reclameaqui.com.br/",
    commercialStatus: "ALLOWED",
    authentication: "Navegação manual pelo usuário",
    cost: "R$ 0 para abertura manual; nenhuma automação ou scraping",
    quota: "Não aplicável ao EDY ScanURL",
    dataSent: "Nenhum dado enviado automaticamente",
    retention: "Nenhum dado coletado",
    caching: "Não aplicável",
    redistribution: "Não aplicável",
    attribution: "Reclame AQUI",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_RECLAME_AQUI_AUTOMATION_ENABLED",
    disabledReason: "DISABLED_BY_POLICY",
  },
  {
    provider: "procon-official-warnings",
    termsUrl: "https://www.gov.br/mj/pt-br/assuntos/seus-direitos/consumidor",
    commercialStatus: "ALLOWED",
    authentication: "Sem fonte nacional agregada provisionada para consulta automática por domínio",
    cost: "R$ 0; integração não provisionada",
    quota: "Varia por órgão e publicação oficial",
    dataSent: "Nenhum dado enviado no MVP",
    retention: "Nenhum dado coletado no MVP",
    caching: "Não aplicável",
    redistribution: "Não aplicável",
    attribution: "Sistema Nacional de Defesa do Consumidor",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_PROCON_ENABLED",
    disabledReason: "DISABLED_NOT_PROVISIONED",
  },
  {
    provider: "business-cnpj-bulk",
    termsUrl: "https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj",
    commercialStatus: "CONDITIONAL",
    authentication: "None for public snapshot",
    cost: "R$ 0; local ingestion/storage not provisioned in MVP",
    quota: "Bulk snapshot",
    dataSent: "None when queried locally",
    retention: "Public company field allowlist only",
    caching: "Snapshot metadata and hash",
    redistribution: "Subject to dataset license and minimization",
    attribution: "Receita Federal / dados.gov.br",
    lastReviewed: "2026-08-30",
    enabled: false,
    killSwitch: "PROVIDER_CNPJ_BULK_ENABLED",
    disabledReason: "DISABLED_NOT_PROVISIONED",
  },
] as const;

export function assertComplianceRegistry(records = providerComplianceRegistry): void {
  for (const record of records) {
    if (record.enabled && record.commercialStatus !== "ALLOWED" && record.provider !== "transparency-passive") {
      throw new Error(`Provider ${record.provider} is enabled without confirmed commercial permission`);
    }
    if (!record.enabled && !record.disabledReason) {
      throw new Error(`Disabled provider ${record.provider} must have an explicit reason`);
    }
  }
}
